---
asyncJob:
  broker: 'amqp://si9ma:rabbitmq@127.0.0.1:5672/'
  default_queue: KillOJ_Judge_Queue
  binding_key: KillOJ_Judge_Queue
  exchange: KillOJ_Exchange
  exchange_type: direct
  prefetch_count: 3

mysql:
  connStr: 'root:mysqlpass@(127.0.0.1:3306)/killoj?charset=utf8&parseTime=True&loc=Local'

redis:
  addrs:
    - '127.0.0.1:7000'
    - '127.0.0.1:7001'
    - '127.0.0.1:7002'
    - '127.0.0.1:7003'
    - '127.0.0.1:7004'
    - '127.0.0.1:7005'
  dialTimeOut: 2000
  readTimeOut: 2000
  writeTimeOut: 2000

concurrency: 3 # concurrency of judger

sandbox:
  exePath: '/home/si9ma/Go/bin/kbox'
  enableLog: true
  logFormat: 'json'
  logPath: 'log/sandbox.log'