---
broker: 'amqp://si9ma:rabbitmq@localhost:5672/'
default_queue: judger

#result_backend: 'redis://localhost:6379'
#result_backend: 'memcache://localhost:11211'
#result_backend: 'mongodb://localhost:27017'
#results_expire_in: 3600000

amqp:
  binding_key: killOJ
  exchange: KillOJ
  exchange_type: direct
  prefetch_count: 3
