version: '3'
services:
  kjudger:
    image: si9ma/kjudger
    build:
      context: .
    environment:
      - KILLOJ_DEBUG=true
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - prod_net
    volumes:
      - ./log:/kjudger/log
      - ./conf:/kjudger/conf
    privileged: true
    command: ["judge","-c","conf/config.yml.dev","judger"]

networks:
  prod_net:
    external: true